name: Compile LaTeX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List files in docs before compilation (debug)
      run: ls -la docs/

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex latexmk

    - name: Build LaTeX document
      run: |
        latexmk -pdf -interaction=nonstopmode -f docs/Formulario.tex

    - name: Move PDF to docs
      run: |
        mv Formulario.pdf docs/

    - name: List files in docs after compilation (debug)
      run: ls -la docs/

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: formulario-pdf
        path: docs/Formulario.pdf
