name: Compile LaTeX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex latexmk

    - name: Build LaTeX document
      run: |
        latexmk -pdf -interaction=nonstopmode Formulario.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: formulario-pdf
        path: Formulario.pdf
